Add option to include other update images
rhinstaller/devel-tools pull request #14
Opened 2020-02-03 17:06 UTC by VladimirSlavik

With this, the Anaconda updates script can now merge other images, such as from add-ons in development.

2020-02-10 17:07 UTC, jkonecny12 requested changes
Other than this it looks good to me.

2020-02-10 17:07 UTC, jkonecny12 commented on anaconda_updates/update_image.py
> +            popen = subprocess.Popen(cmd, shell=True)
Please use [subprocess.run()](https://docs.python.org/3/library/subprocess.html#subprocess.run) here.

2020-02-11 11:09 UTC, VladimirSlavik commented on anaconda_updates/update_image.py
> +            popen = subprocess.Popen(cmd, shell=True)
Solved!

2020-02-14 13:36 UTC, jkonecny12 approved these changes
Looks good to me now.

2020-02-14 13:36 UTC, merged

2020-02-14 13:38 UTC, VladimirSlavik commented
Thank you!